# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-05 11:34:05
"""
import arcpy

def BLMpointsSJFieldOffices():  # BLMpointsSJFieldOffices

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    InFormFuelsFeatureCsvExtract_Points = "Regions\\InFormFuelsFeatureCsvExtract_Points"
    blm_natl_admu_field_poly_webpub_1 = "Location Unit Layers\\blm_natl_admu_field_poly_webpub_1"

    # Process: Spatial Join (Spatial Join) (analysis)
    InFormFuelsFeatu_SpatialJoin6 = "C:\\Users\\warmstrong\\Documents\\work\\InFORM\\20230912 NFPORS InFORM Crosswalk Script\\BIA Crosswalk\\BIA Crosswalk.gdb\\InFormFuelsFeatu_SpatialJoin6"
    arcpy.analysis.SpatialJoin(target_features=InFormFuelsFeatureCsvExtract_Points, join_features=blm_natl_admu_field_poly_webpub_1, out_feature_class=InFormFuelsFeatu_SpatialJoin6, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="GUID \"GUID\" true true false 8000 Text 0 0,First,#,Regions\\InFormFuelsFeatureCsvExtract_Points,GUID,0,8000;ADMU_NAME \"Administrative Unit Name\" true true false 40 Text 0 0,First,#,Location Unit Layers\\blm_natl_admu_field_poly_webpub_1,ADMU_NAME,0,40", match_option="INTERSECT", search_radius="", distance_field_name="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb", workspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb"):
        BLMpointsSJFieldOffices()
