# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2024-01-05 10:27:21
"""
import arcpy

def BLMregions():  # BLMregions

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    InFormFuelsFeatureCsvExtract_Points = "Regions\\InFormFuelsFeatureCsvExtract_Points"
    blm_regions = "Regions\\blm_regions"

    # Process: Spatial Join (Spatial Join) (analysis)
    InFormFuelsFeatu_SpatialJoin5 = "C:\\Users\\warmstrong\\Documents\\work\\InFORM\\20230912 NFPORS InFORM Crosswalk Script\\BIA Crosswalk\\BIA Crosswalk.gdb\\InFormFuelsFeatu_SpatialJoin5"
    arcpy.analysis.SpatialJoin(target_features=InFormFuelsFeatureCsvExtract_Points, join_features=blm_regions, out_feature_class=InFormFuelsFeatu_SpatialJoin5, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="GUID \"GUID\" true true false 8000 Text 0 0,First,#,Regions\\InFormFuelsFeatureCsvExtract_Points,GUID,0,8000;ADMIN_ST \"Administrative State Code\" true true false 2 Text 0 0,First,#,Regions\\blm_regions,ADMIN_ST,0,2;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,Regions\\blm_regions,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,Regions\\blm_regions,Shape_Area,-1,-1", match_option="INTERSECT", search_radius="", distance_field_name="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb", workspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb"):
        BLMregions()
