# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-13 09:33:33
"""
import arcpy

def fwsRegions():  # fwsRegions

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    InFormFuelsFeatureCsvExtract_Points = "InFormFuelsFeatureCsvExtract_Points"
    fws_regions = "fws_regions"

    # Process: Spatial Join (Spatial Join) (analysis)
    InFormFuelsFeatu_SpatialJoin3 = "C:\\Users\\warmstrong\\Documents\\work\\InFORM\\20230912 NFPORS InFORM Crosswalk Script\\BIA Crosswalk\\BIA Crosswalk.gdb\\InFormFuelsFeatu_SpatialJoin3"
    arcpy.analysis.SpatialJoin(target_features=InFormFuelsFeatureCsvExtract_Points, join_features=fws_regions, out_feature_class=InFormFuelsFeatu_SpatialJoin3, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="GUID \"GUID\" true true false 8000 Text 0 0,First,#,InFormFuelsFeatureCsvExtract_Points,GUID,0,8000;REGNAME \"REGNAME\" true true false 50 Text 0 0,First,#,fws_regions,REGNAME,0,50;Shape_Length \"Shape_Length\" false true true 8 Double 0 0,First,#,fws_regions,Shape_Length,-1,-1;Shape_Area \"Shape_Area\" false true true 8 Double 0 0,First,#,fws_regions,Shape_Area,-1,-1", match_option="INTERSECT", search_radius="", distance_field_name="")

