# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-21 09:54:07
"""
import arcpy

def Ownership_Dep_Unit_Agency(points, JU_layer, workspace):  # OwnershipDepartment/OwnershipUnit/OwnershipAgency

    
    arcpy.env.overwriteOutput = True

    Table = "InFormFuelsFeatureCsvExtract"
    Points = "points"
    WFDSS_Jurisdictional_Agency = "WFDSS_Jurisdictional_Agency"

    # Spatial Join points to WFDSS_Jurisdictional_Agency
    points_SpatialJoin1 = "C:\\Users\\warmstrong\\Documents\\work\\InFORM\\20230912 NFPORS InFORM Crosswalk Script\\BIA Crosswalk\\BIA Crosswalk.gdb\\points_SpatialJoin1"
    arcpy.analysis.SpatialJoin(Points, WFDSS_Jurisdictional_Agency, points_SpatialJoin1, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="GUID \"GUID\" true true false 8000 Text 0 0,First,#,points,GUID,0,8000;JurisdictionalUnitName \"JurisdictionalUnitName\" true true false 100 Text 0 0,First,#,WFDSS_Jurisdictional_Agency,JurisdictionalUnitName,0,100;LegendLandownerCategory \"LegendLandownerCategory\" true true false 20 Text 0 0,First,#,WFDSS_Jurisdictional_Agency,LegendLandownerCategory,0,20;LandownerDepartment \"LandownerDepartment\" true true false 80 Text 0 0,First,#,WFDSS_Jurisdictional_Agency,LandownerDepartment,0,80", match_option="INTERSECT", search_radius="", distance_field_name="")

