# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-09-22 15:34:44
"""
import arcpy

def Tribes():  # Tribes

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    InFormFuelsFeatureCsvExtract_Points = "InFormFuelsFeatureCsvExtract_Points"
    TribeName = "TribeName"

    # Process: Add Field (Add Field) (management)
    TribeName_2_ = arcpy.management.AddField(in_table=TribeName, field_name="tribe_name_edit", field_type="TEXT", field_precision=None, field_scale=None, field_length=None, field_alias="", field_is_nullable="NULLABLE", field_is_required="NON_REQUIRED", field_domain="")[0]

    # Process: Calculate Field (Calculate Field) (management)
    TribeName_3_ = arcpy.management.CalculateField(in_table=TribeName_2_, field="tribe_name_edit", expression="!NAME!", expression_type="PYTHON3", code_block="", field_type="TEXT", enforce_domains="NO_ENFORCE_DOMAINS")[0]

    # Process: Spatial Join (Spatial Join) (analysis)
    InFormFuelsFeatu_SpatialJoin2 = "C:\\Users\\warmstrong\\Documents\\work\\InFORM\\20230912 NFPORS InFORM Crosswalk Script\\BIA Crosswalk\\BIA Crosswalk.gdb\\InFormFuelsFeatu_SpatialJoin2"
    arcpy.analysis.SpatialJoin(target_features=InFormFuelsFeatureCsvExtract_Points, join_features=TribeName_3_, out_feature_class=InFormFuelsFeatu_SpatialJoin2, join_operation="JOIN_ONE_TO_ONE", join_type="KEEP_ALL", field_mapping="guid \"guid\" true true false 255 Text 0 0,First,#,InFormFuelsFeatureCsvExtract_Points,GUID,0,8000;tribe_name \"tribe_name\" true true false 255 Text 0 0,First,#,TribeName,tribe_name_edit,0,255", match_option="INTERSECT", search_radius="", distance_field_name="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb", workspace=r"C:\Users\warmstrong\Documents\work\InFORM\20230912 NFPORS InFORM Crosswalk Script\BIA Crosswalk\BIA Crosswalk.gdb"):
        Tribes()
